# Generated by Django 4.1.1 on 2022-11-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('refno', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('subsection', models.CharField(max_length=100)),
                ('acts', models.CharField(max_length=100)),
                ('charges', models.TextField()),
            ],
        ),
    ]
