# Generated by Django 4.1.2 on 2022-11-27 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('nin', models.DecimalField(decimal_places=0, max_digits=20)),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.crime')),
            ],
        ),
    ]
