# Generated by Django 4.1.2 on 2022-11-27 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0001_initial'),
        ('criminal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='charge',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='crime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crime.crime'),
        ),
    ]
